global:
  # -- imagePullSecrets
  # Example --> imagePullSecrets: [ "secret" ]
  imagePullSecrets: []
  registry: ""
  pullPolicy: ""

image:
  registry: 347694409649.dkr.ecr.us-west-2.amazonaws.com
  repository: veego/mobile-api
  tag: staging
  pullPolicy: Always

replicaCount: 1

containerPort: 8080

services:
  - name: mobile-api
    port: 80
    targetPort: 8080
    protocol: TCP
    type: NodePort
    selector:
      app: mobile-api

ingress:
  enabled: true
  ingressClassName: ""
  hosts:
    - mobile-api.example.domain

extraConfigMap: []
extraSecret: []

configMap:
  ## VEEGO_SERVER_TIME_ZONE: "UTC"
  VEEGO_SERVER_TIME_ZONE: ""
  ## VEEGO_KAFKA_HOSTS: "kafka-node-1:9092,kafka-node-2:9092,kafka-node-3:9092,kafka-node-4:9092"
  # VEEGO_KAFKA_HOSTS: ""
  ## VEEGO_REDIS_HOSTS: "redis-node-1:6379,redis-node-2:6379,redis-node-3:6379"
  # VEEGO_REDIS_HOSTS: ""
  ## VEEGO_SQL_URL: "jdbc:postgresql://postgresql-master:5424/veegodb"
  # VEEGO_SQL_URL: ""
  ## VEEGO_ZIPKIN_BASE_URL: "http://localhost:9411"
  # VEEGO_ZIPKIN_BASE_URL: ""
  VEEGO_SMTP_USERNAME: ""
  VEEGO_SMTP_SMTP_PORT: "587"
  VEEGO_SMTP_SMTP_DEBUG: "false"
  VEEGO_SMTP_HOST: ""
  VEEGO_JWT_EXPIRATION: "360000000"
  VEEGO_SMTP_REGISTRATION_SENDER: ""
  VEEGO_SMTP_REGISTRATION_SUBJECT: ""
  VEEGO_DEV_AGENT_PREFIX: "D"
  VEEGO_STAGING_AGENT_PREFIX: "S"
  VEEGO_CELLCOM_AGENT_PREFIX: "C"
  VEEGO_RAKUTEN_AGENT_PREFIX: "R"
  VEEGO_LOGIN_URL_DEV: "https://mobile-api.dev.example.domain"
  VEEGO_LOGIN_URL_STAGING: "https://mobile-api.stage.example.domain/"
  VEEGO_CURRENT_ENV: "S"
  VEEGO_IGNORED_MAC_ADDRESSES: ""
  ## LOGSTASH_HOST: "logstash-service:8080"
  # LOGSTASH_HOST: ""

secret:
  # VEEGO_KAFKA_USERNAME: ""
  # VEEGO_KAFKA_PASSWORD: ""
  # VEEGO_REDIS_PASSWORD: ""
  # VEEGO_SQL_USERNAME: ""
  # VEEGO_SQL_PASSWORD: ""
  # VEEGO_SMTP_PASSWORD: ""
  # VEEGO_JWT_SECRET: ""
  # VEEGO_KAFKA_SASL_USERNAME: ""
  # VEEGO_KAFKA_SASL_PASSWORD: ""
  # VEEGO_KAFKA_SASL_SERVICE_NAME: ""
