global:
  imagePullSecrets: []

image:
  registry: 347694409649.dkr.ecr.us-west-2.amazonaws.com
  repository: veego/malfunctions-counters-cleaner
  tag: staging
  pullPolicy: Always

replicaCount: 1

configMap:
  ## VEEGO_REDIS_HOSTS: "redis-node-1:6379,redis-node-2:6379,redis-node-3:6379"
  VEEGO_REDIS_HOSTS: ""
  AGENT_MALFUNCTIONS_CLEANER_SCHEDULING: "0 0/10 * * * ?"
  ## VEEGO_ZIPKIN_BASE_URL: "http://localhost:9411"
  VEEGO_ZIPKIN_BASE_URL: ""
  ## LOGSTASH_HOST: "logstash-service:8080"
  LOGSTASH_HOST: ""
