---
{{- $chart_name := .Chart.Name }}
{{- $release_name := .Release.Name }}
{{- $release_namespace := .Release.Namespace }}
{{- if .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $chart_name }}-secret
  namespace: {{ $release_namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    meta.helm.sh/release-name: {{ $release_name | quote }}
    meta.helm.sh/release-namespace: {{ $release_namespace | quote }}
    release: {{ $release_name }}
type: Opaque
data:
  {{- toYaml .Values.secret | nindent 2 }}
{{- end }}
