---
{{- $chart_name := .Chart.Name }}
{{- $release_name := .Release.Name }}
{{- $release_namespace := .Release.Namespace }}
{{- if .Values.configMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $chart_name }}-configmap
  namespace: {{ $release_namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    app: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  {{- toYaml .Values.configMap | nindent 2 }}
{{- end }}
