---
{{- $chart_name := .Chart.Name }}
{{- $release_name := .Release.Name }}
{{- $release_namespace := .Release.Namespace }}
{{- if .Values.services -}}
{{- range $services := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if $services.annotations -}}
  {{- with $services.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  name: {{ $services.name }}
  namespace: {{ $release_namespace }}
  {{- if $services.labels -}}
  {{- with $services.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  {{- if $services.selector -}}
  {{- with $services.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  type: {{ $services.type | default "NodePort" }}
  ports:
    - port: {{ $services.port | default "80" }}
      protocol: {{ $services.protocol | default "TCP" }}
      {{- if $services.targetPort }}
      targetPort: {{ $services.targetPort }}
      {{ end }}
      {{- if $services.nodePort }}
      nodePort: {{ $services.nodePort }}
      {{ end }}
{{ end }}
{{ end }}
