global:
  imagePullSecrets: []

image:
  registry: 347694409649.dkr.ecr.us-west-2.amazonaws.com
  repository: veego/home-score-handler
  tag: staging
  pullPolicy: Always

replicaCount: 1


configMap:
  ## VEEGO_REDIS_HOSTS: "redis-node-1:6379,redis-node-2:6379,redis-node-3:6379"
  VEEGO_REDIS_HOSTS: ""
  ## VEEGO_SQL_URL: "jdbc:postgresql://postgresql-master:5424/veegodb"
  VEEGO_SQL_URL: ""
  AGENT_HOME_SCORE_SCHEDULING: "0 0 0 * * ?"
  ## VEEGO_ZIPKIN_BASE_URL: "http://localhost:9411"
  VEEGO_ZIPKIN_BASE_URL: ""
  ## LOGSTASH_HOST: "logstash-service:8080"
  LOGSTASH_HOST: ""


secret:
  VEEGO_KAFKA_USERNAME: ""
  VEEGO_KAFKA_PASSWORD: ""
  VEEGO_REDIS_PASSWORD: ""
  VEEGO_SQL_USERNAME: ""
  VEEGO_SQL_PASSWORD: ""
  VEEGO_KAFKA_SASL_USERNAME: ""
  VEEGO_KAFKA_SASL_PASSWORD: ""
  VEEGO_KAFKA_SASL_SERVICE_NAME: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
