global:
  imagePullSecrets: []

image:
  registry: 347694409649.dkr.ecr.us-west-2.amazonaws.com
  repository: veego/api-gateway
  tag: staging
  pullPolicy: Always

replicaCount: 1

containerPort: 8889

services:
  - name: api-gateway-public
    port: 80
    targetPort: 8889
    protocol: TCP
    type: NodePort
    selector:
      app: api-gateway

ingress:
  enabled: true
  ingressClassName: "nginx"
  hosts:
    - api-gateway.example.domain
    - dashboard.example.domain


configMap:
  VEEGO_SERVER_TIME_ZONE: "Asia/Jerusalem"
  ## VEEGO_KAFKA_HOSTS: "kafka-node-1:9092,kafka-node-2:9092,kafka-node-3:9092,kafka-node-4:9092"
  VEEGO_KAFKA_HOSTS: ""
  ## VEEGO_REDIS_HOSTS: "redis-node-1:6379,redis-node-2:6379,redis-node-3:6379"
  VEEGO_REDIS_HOSTS: ""
  ## VEEGO_SQL_URL: "jdbc:postgresql://postgresql-master:5424/veegodb"
  VEEGO_SQL_URL: ""
  ## AWS_ACCOUNT_ID: "XXXXXXXXXXXX"
  AWS_ACCOUNT_ID: ""
  ## AWS_REGION: "us-west-2"
  AWS_REGION: ""
  ## VEEGO_ZIPKIN_BASE_URL: "http://localhost:9411"
  VEEGO_ZIPKIN_BASE_URL: ""
  ##   VEEGO_SIGN_OUT_URL: "https://keycloak.example.domain/auth/realms/veego/protocol/openid-connect/logout?redirect_uri=https://dashboard.example.domain/oauth2/sign_out"
  VEEGO_SIGN_OUT_URL: ""
  QUICKSIGHT_ANALYTICS_DASHBOARD_ID: "11c2aa38-4f38-470f-8dc0-950046bce999"
  QUICKSIGHT_MARKETING_DASHBOARD_ID: "d4e521f9-840a-4309-889c-689194045dc6"
  QUICKSIGHT_MY_HOME_DASHBOARD_ID: "b24234ff-508e-47f6-b142-ca10d956ac0c"
  QUICKSIGHT_MY_EXPERIENCE_DASHBOARD_ID: "d3228250-8ebb-48e5-b959-1c176722e5cb"
  QUICKSIGHT_MY_SERVICES_DASHBOARD_ID: "6ea9e8bc-0a8e-4045-9dfe-b12e08bbbc5f"
  QUICKSIGHT_MY_MALFUNCTIONS_DASHBOARD_ID: "06ee0fa6-c2d9-4d15-af33-500111df4734"
  ## LOGSTASH_HOST: "logstash-service:8080"
  LOGSTASH_HOST: ""


secret:
  VEEGO_KAFKA_USERNAME: ""
  VEEGO_KAFKA_PASSWORD: ""
  VEEGO_REDIS_PASSWORD: ""
  VEEGO_SQL_USERNAME: ""
  VEEGO_SQL_PASSWORD: ""
  VEEGO_KAFKA_SASL_USERNAME: ""
  VEEGO_KAFKA_SASL_PASSWORD: ""
  VEEGO_KAFKA_SASL_SERVICE_NAME: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
