global:
  # -- imagePullSecrets
  # Example --> imagePullSecrets: [ "secret" ]
  imagePullSecrets: []
  registry: ""
  pullPolicy: ""

image:
  registry: 347694409649.dkr.ecr.us-west-2.amazonaws.com
  repository: veego/services-name-resolver-api-gateway
  tag: staging
  pullPolicy: Always

replicaCount: 1

containerPort: 8080

services:
  - name: services-name-resolver-api-gateway-public
    port: 80
    targetPort: 8080
    protocol: TCP
    type: ClusterIP
    selector:
      app: services-name-resolver-api-gateway

ingress:
  enabled: true
  ingressClassName: ""
  hosts:
    - api.example.domain

extraConfigMap: []
extraSecret: []

configMap:
  # REDIS_HOST: ""
  ## LOGSTASH_HOST: "logstash-service:8080"
  # LOGSTASH_HOST: ""


secret:
  # REDIS_PASSWORD: ""
